services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./test_db:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./certs/ca.pem:/etc/mysql/certs/ca.pem
      - ./certs/server-cert.pem:/etc/mysql/certs/server-cert.pem
      - ./certs/server-key.pem:/etc/mysql/certs/server-key.pem
  api:
    build: ./api
    container_name: employees-api
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "8500:8500"
    depends_on:
      - mysql

  web:
    build: ./web
    container_name: web-ui
    environment:
      API_BASE: http://api:8500
      APP_USER: ${APP_USER:-admin}
      APP_PASSWORD: ${APP_PASSWORD:-password}
      SECRET_KEY: ${SECRET_KEY:-changeme}
    volumes:
      - ./web/certs:/app/certs
    ports:
      - "443:443"
    depends_on:
      - api
